//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.InterestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InterestService.IInterestService")]
    public interface IInterestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestService/CalculateCompoundInterest", ReplyAction="http://tempuri.org/IInterestService/CalculateCompoundInterestResponse")]
        double CalculateCompoundInterest(double balance, double annualIntRatePercent, int years, int compoundsPerYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestService/CalculateCompoundInterest", ReplyAction="http://tempuri.org/IInterestService/CalculateCompoundInterestResponse")]
        System.Threading.Tasks.Task<double> CalculateCompoundInterestAsync(double balance, double annualIntRatePercent, int years, int compoundsPerYear);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterestServiceChannel : Bank.InterestService.IInterestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterestServiceClient : System.ServiceModel.ClientBase<Bank.InterestService.IInterestService>, Bank.InterestService.IInterestService {
        
        public InterestServiceClient() {
        }
        
        public InterestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalculateCompoundInterest(double balance, double annualIntRatePercent, int years, int compoundsPerYear) {
            return base.Channel.CalculateCompoundInterest(balance, annualIntRatePercent, years, compoundsPerYear);
        }
        
        public System.Threading.Tasks.Task<double> CalculateCompoundInterestAsync(double balance, double annualIntRatePercent, int years, int compoundsPerYear) {
            return base.Channel.CalculateCompoundInterestAsync(balance, annualIntRatePercent, years, compoundsPerYear);
        }
    }
}
